export const SURVEY_QUESTIONS = {
  REGULAR: [
    { id: 1, question: "Which social media platform do you use most frequently?", options: ["Facebook", "Twitter", "Instagram", "TikTok"] },
    { id: 2, question: "How often do you shop online?", options: ["Weekly", "Monthly", "A few times a year", "Never"] },
    { id: 3, question: "What is your preferred mode of transport in the city?", options: ["Matatu", "Boda Boda", "Taxi (Uber/Bolt)", "Personal Car"] },
    { id: 4, question: "Which brand of cooking oil is your favorite?", options: ["Fresh Fri", "Elianto", "Golden Fry", "Other"] },
    { id: 5, question: "How do you prefer to watch movies?", options: ["Cinema", "Netflix/Streaming", "TV Channels", "DVDs"] },
    { id: 6, question: "What type of content do you enjoy most on YouTube?", options: ["Music Videos", "Comedy Skits", "Tutorials", "News & Documentaries"] },
    { id: 7, question: "Which mobile network provider do you use?", options: ["Safaricom", "Airtel", "Telkom", "Faiba"] },
    { id: 8, question: "What's your favorite soft drink?", options: ["Coca-Cola", "Fanta", "Sprite", "Krest"] },
    { id: 9, question: "How many times do you eat out in a month?", options: ["0-2 times", "3-5 times", "6-10 times", "More than 10"] },
    { id: 10, question: "What factor is most important when buying a smartphone?", options: ["Price", "Camera Quality", "Battery Life", "Brand Name"] },
  ],
  VIP: [
    { id: 1, question: "Which bank provides the best mobile banking experience for you?", options: ["Equity Bank", "KCB", "Co-operative Bank", "Absa"] },
    { id: 2, question: "What is your primary source for news and information?", options: ["Television", "Social Media", "Newspapers", "Online News Sites"] },
    { id: 3, question: "Which supermarket do you visit most often for your groceries?", options: ["Naivas", "Quickmart", "Carrefour", "Local Kiosk"] },
    { id: 4, question: "When choosing an internet service provider, what is most important?", options: ["Speed", "Price", "Reliability", "Customer Service"] },
    { id: 5, question: "How much do you typically spend on data bundles per month?", options: ["< KES 500", "KES 500 - 1000", "KES 1001 - 2000", "> KES 2000"] },
    { id: 6, question: "Which of these fast-food chains is your favorite?", options: ["KFC", "Chicken Inn", "Big Square", "Java House"] },
    { id: 7, question: "What influences your decision to try a new restaurant?", options: ["Friend's Recommendation", "Online Reviews", "Advertisements", "Location"] },
    { id: 8, question: "Which type of insurance cover do you consider most essential?", options: ["Health Insurance", "Car Insurance", "Life Insurance", "None"] },
    { id: 9, question: "How do you feel about online/digital lending apps?", options: ["Very Helpful", "Somewhat Helpful", "Neutral", "Untrustworthy"] },
    { id: 10, question: "What's your preferred payment method for online purchases?", options: ["M-Pesa", "Credit/Debit Card", "PayPal", "Cash on Delivery"] },
  ],
  VVIP: [
    { id: 1, question: "Which high-end residential area in Nairobi would you prefer to live in?", options: ["Karen", "Runda", "Muthaiga", "Kileleshwa"] },
    { id: 2, question: "What is your preferred airline for international travel?", options: ["Kenya Airways", "Emirates", "Ethiopian Airlines", "Qatar Airways"] },
    { id: 3, question: "Which luxury car brand do you admire the most?", options: ["Mercedes-Benz", "BMW", "Range Rover", "Porsche"] },
    { id: 4, question: "When investing, which asset class are you most interested in?", options: ["Real Estate", "Stocks/Equities", "Government Bonds", "Cryptocurrency"] },
    { id: 5, question: "What is your favorite premium alcoholic beverage brand?", options: ["Johnnie Walker", "Hennessy", "Cîroc", "Don Julio"] },
    { id: 6, question: "Which exclusive club or lounge do you prefer for socializing?", options: ["Capital Club", "Kempinski", "B-Club", "I don't go to clubs"] },
    { id: 7, question: "For a vacation, which type of destination do you prefer?", options: ["Beach Resort (e.g., Diani)", "Safari/Lodge (e.g., Maasai Mara)", "International City", "Mountain Retreat"] },
    { id: 8, question: "Which designer clothing brand appeals to you the most?", options: ["Gucci", "Louis Vuitton", "Versace", "I prefer local designers"] },
    { id: 9, question: "How do you primarily manage your wealth and investments?", options: ["Personal Management", "Financial Advisor", "Bank's Wealth Management", "Family Office"] },
    { id: 10, question: "What is the most important factor for you in a luxury hotel?", options: ["Service Quality", "Exclusivity/Privacy", "Amenities (Spa, Pool)", "Location and Views"] },
  ],
};